#kubectl get secret -n monitoring elasticsearch-es-elastic-user -o=jsonpath='{.data.elastic}'
apiVersion: v1
kind: Secret
metadata:
  name: jaeger-storage-secret
  namespace: monitoring
type: Opaque
data:
  ES_PASSWORD: <base64 encoded password>
  ES_USERNAME: ZWxhc3RpYw== #elastic