apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
  name: jaeger-nodeport
  namespace: monitoring
spec:
  ports:
    - name: http-query
      protocol: TCP
      port: 16686
      targetPort: 16686
      nodePort: 30012
  selector:
    app: jaeger
  type: NodePort